### ISSUE TITLE
Unsupported version control system (unknown).

### ISSUE THREAD

**Issue by lviggiani** [ymattw/coderev#7]
Hi,
when I try to run the followimg command:

    $ svn diff file:///var/svn/client -r 118 | ./coderev.sh

I get this error:

    Unsupported version control system (unknown).
    svn: Can't write to stream: Broken pipe

Do I miss any dependencies?

It happens with both subversion 1.6 and 1.7

**Comment by ymattw** [comment]
Try run coderev.sh with bash -x. You will see the debug message.

**Comment by lviggiani** [comment]
$ ./coderev.sh -x
    ./coderev.sh: illegal option -- x

:(

**Comment by lviggiani** [comment]
+ [[ -L ./coderev.sh ]]
+++ dirname ./coderev.sh
++ cd .
++ pwd -P
+ BINDIR=/root/coderev-master
++ basename ./coderev.sh
+ PROG_NAME=coderev.sh
+ CODEDIFF=/root/coderev-master/codediff.py
+ . /root/coderev-master/libsvn.sh
+ . /root/coderev-master/libcvs.sh
++ detect_vcs
++ local ident=
++ [[ -f .svn/entries ]]
++ [[ -f CVS/Entries ]]
++ ident=unknown
++ echo unknown
+ set_vcs_ops unknown
+ local ident=unknown
+ eval vcs_get_banner=unknown_get_banner
++ vcs_get_banner=unknown_get_banner
+ eval vcs_get_repository=unknown_get_repository
++ vcs_get_repository=unknown_get_repository
+ eval vcs_get_project_path=unknown_get_project_path
++ vcs_get_project_path=unknown_get_project_path
+ eval vcs_get_working_revision=unknown_get_working_revision
++ vcs_get_working_revision=unknown_get_working_revision
+ eval vcs_get_active_list=unknown_get_active_list
++ vcs_get_active_list=unknown_get_active_list
+ eval vcs_get_diff=unknown_get_diff
++ vcs_get_diff=unknown_get_diff
+ eval vcs_get_diff_opt=unknown_get_diff_opt
++ vcs_get_diff_opt=unknown_get_diff_opt
+ CODEREV_NAME=
+ COMMENT_FILE=
+ COMMENTS=
+ OUTPUT_DIR=
+ PATCH_LVL=0
+ REV_ARG=
+ REVERSE_PATCH=false
+ WRAP_NUM=
+ OVERWRITE=false
+ getopts d:F:hm:o:p:r:w:y op
+ shift 0
+ PATHNAME=.
+ [[ -t 0 ]]
+ RECV_STDIN=true
++ unknown_get_banner
++ echo unknown
++ return 1
+ BANNER=unknown
+ echo 'Unsupported version control system (unknown).'
Unsupported version control system (unknown).
+ exit 1

**Comment by ymattw** [comment]
cd to your svn workspace first. But I would recommend you use cdiff
instead, see the readme file :)

**Comment by lviggiani** [comment]
So that is supposed to be run on a working copy only?

**Comment by ymattw** [comment]
That's true. It requires a local copy to detect vcs type.  Use cdiff for your case buddy :).  https://github.com/ymattw/cdiff

**Comment by lviggiani** [comment]
Ok, thanks!
But can cdiff output be converted to html diff?

**Comment by ymattw** [comment]
No, sorry. I don't have any plan to implement that because github/gitlab both support nice code review interface.  You should move to git really :)

**Comment by lviggiani** [comment]
Ok, thanks!
